export const INIT_ACTVIVITIES = 'INIT_ACTVIVITIES';
export const LOADING_ACTIVITIES = 'LOADING_ACTIVITIES';
export const LOADED_ACTIVITIES = 'LOADED_ACTIVITIES';
export const ERROR_ACTIVITIES = 'ERROR_ACTIVITIES';
export const LOAD_USER_ACTIVITIES = 'LOAD_USER_ACTIVITIES';
export const LOAD_ACTIVITY = 'LOAD_MY_ACTIVITY';
