export const INIT_ACTVIVITIES = 'INIT_ACTVIVITIES';
export const LOADING_ACTIVITIES = 'LOADING_ACTIVITIES';
export const LOADED_ACTIVITIES = 'LOADED_ACTIVITIES';
export const ERROR_ACTIVITIES = 'ERROR_ACTIVITIES';
export const SET_LOGIN_TOKEN = 'SET_LOGIN_TOKEN';
